### PR TITLE
fix: fix various typos

### PR DESCRIPTION
**Pull request by ccampo133**
I noticed quite a few typos in the repository, so I've corrected them in this PR. Unfortunately, two of the main classes (`CompontentGroup` and `CompontentGroupManager`) were misspelled, so renaming them to correct the spelling is a breaking change for existing users and hence requires a major version bump. I included the version bump in this PR.

### CODE REVIEW

**Comment by einarf** [comment]
Wow. That was a lot of typos 😄 

Major bump is more than ok. Probably need up update tests and get that visible flag in.. and 2.0 should be quick to sort out.

**Comment by einarf** [comment]
Thank you again!

**Comment by ccampo133** [comment]
No problem. Regarding the visible flag, I'll have a PR for that shortly.

**Comment by einarf** [comment]
At least I managed to spell `Component` correctly in the class 😄 

I'll keep my eyes open for the PR. Should be more than reasonable to push a 2.0 to PyPI in a few.

**Pull request merged**
