### PR TITLE
add schedules

### PR DESCRIPTION
**Pull request by neutron-ah**

### CODE REVIEW

**Comment by einarf** [comment]
Thanks! I will look at this very soon.

**Comment by einarf** [comment]
Thanks. Just merging this as I'm working with tests.

**Comment by neutron-ah** [comment]
Thank! Are you planning to upgrade the pypi package?

**Comment by einarf** [comment]
Yup. Doing some other maintenance and a new version will be pushed. Likely tonight.

**Comment by neutron-ah** [comment]
Schedule can create only in datetime format without seconds:
`scheduled_at=datetime.datetime.now().strftime('%Y-%m-%d %H:%M'))`

**Comment by einarf** [comment]
Yup. I noticed in cachet logs. There was a missing `completed_at` in create and some other smaller stuff like docstrings. Also added unit and live tests.

3.1.0 should be on pypi now.

**Comment by neutron-ah** [comment]
There is cachet bug in schedules – when completed_at is set then no Maintaince object is displayed on main page.

**Comment by einarf** [comment]
ah right. Still the api supports setting it, so we are fine on this side.

The only confusing thing is the `components` parameter is supports. You can pass in a list of components the maintenance event affects, but nothing is displayed in cachet web. I was unsure if it actually had any function and left it out for now.

When I think of it.. it might affect the `notify` parameter triggering notification to users subscribed to the affected components.

**Comment by einarf** [comment]
Everything working ok with new version?

**Comment by neutron-ah** [comment]
Yes, everything is great. Thanks a lot for your project!

**Pull request merged**
